name: Dev CI/CD
on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
  workflow_dispatch:

env:
  CI: false
  env_npmrc: ${{ secrets.ENV_NPMRC }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: import env file
        run: |
          touch ./.npmrc && echo "$env_npmrc" >> ./.npmrc

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # PDFWala Image
      - name: build && push pdfwala
        id: build-push-pdfwala
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: rumsan/pdfwala:dev
